### ISSUE TITLE
&gt; not handled properly

### ISSUE THREAD

**Issue by katattakd** [wilsonzlin/hyperbuild#1]
When hyperbuild is fed HTML containing `&gt;`, it results in bizarre and unpredictable behavior. An example of this is below.

Input:
```html
<!DOCTYPE html><p>line one<br>
line two<br>
&lt;test&gt;<br>
line three</p>
```

Expected output:
```html
<!DOCTYPE html><p>line one<br>line two<br>&lt;test&gt;<br>line three</p>
```

Actual output:
```html
<!DOCTYPE html><p>line one<br> line two<br> &LTtest><br> line threehree</p>
```

**Comment by wilsonzlin** [comment]
Hey, thanks for raising. The minifier modifies the source array in place, so it looks like it minified correctly and left the remaining source characters in place (the minified code ends after `three`, as the closing tag for `p` is minified away).

If the Rust library was used, the function returns the minified length if you want to truncate or take a slice of the vector/array. I will add more documentation and wrapper functions to make it a bit easier to use.

There's a space after each `<br>` because they are within a `<p>` which collapses whitespace (including newlines) instead of removing them completely (config to change this will come soon). The `&lt;` is changed to `&LT` because it's shorter, and `&gt;` doesn't need to be encoded so it's decoded.

**Comment by katattakd** [comment]
> Hey, thanks for raising. The minifier modifies the source array in place, so it looks like it minified correctly and left the remaining source characters in place (the minified code ends after three, as the closing tag for p is minified away).
Oh I didn't realize it leaves the remaining source characters in place. You should probably make that a bit clearer in the documentation, I thought this was a bug.
I'll close the issue now.
